apiVersion: apps/v1
kind: Deployment
metadata:
  name: zap
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zap
  template:
    metadata:
      labels:
        app: zap
    spec:
      containers:
        - name: zap
          image: owasp/dependency-check:latest
          args: ["zap.sh", "-daemon", "-port", "8080", "-host", "0.0.0.0"]
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zap
spec:
  type: NodePort
  selector:
    app: zap
  ports:
    - port: 8080
      targetPort: 8081
      nodePort: 30081
